apiVersion: milvus.io/v1alpha1
kind: MilvusCluster
metadata:
  name: milvus-client20
  namespace: qa-milvus
  labels:
    app: milvus
spec:
  components:
    image: "harbor.zilliz.cc/milvus/milvus:master-20211117-ba99779"
    dataNode:
      replicas: 1
    proxy:
      serviceType: LoadBalancer
  dependencies: {}