apiVersion: v1
kind: Pod
metadata:
  labels:
    app: milvus
    componet: testframework
spec:
  containers:
  - name: milvus-testframework
    image: registry.zilliz.com/milvus/milvus-test:v0.2
    command:
    - cat
    tty: true
