simple_chaos:
  collections:
    -
      milvus: null
      before:
        - 
          interface_name: create_collection
          params:
            data_type: local
            dimension: 128
        - 
          interface_name: insert
          params:
            batch_size: 5000
            collection_size: 100000
      processing:
        interface_name: flush
        params: null
        chaos:
          kind: PodChaos
          action: pod-kill
          param:
            name: minio
            cron: ""
      after:
        interface_name: flush
        params: null
      assertions:
        - assertion
          processing: failed_with_exception
        - assertion
          after: pass