simple_chaos:
  collections:
    -
      milvus: null
      before:
        - 
          interface_name: create_collection
          params:
            data_type: local
            dimension: 128
        - 
          interface_name: insert
          params:
            batch_size: 5000
            collection_size: 100000
        - interface_name: create_index
          params:
            metric_type: l2
            index_type: ivf_flat
            index_param:
              nlist: 16384
      processing:
        interface_name: flush
        params: null
        chaos:
          kind: PodChaos
          spec:
            action: pod-kill
            mode: one
            selector:
              namespaces:
                - milvus
              labelSelectors:
                "app.kubernetes.io/instance": etcd
            scheduler:
              cron: "@every 20s"
      after:
        interface_name: flush
        params: null
      assertions:
        - assertion
          processing: failed_with_exception
        - assertion
          after: pass