apiVersion: v1
kind: Pod
metadata:
  labels:
    app: milvus
    componet: test
spec:
  containers:
  - name: milvus-test-env
    image: registry.zilliz.com/milvus/milvus-test-env:v0.3
    command:
    - cat
    tty: true
    volumeMounts:
    - name: kubeconf
      mountPath: /root/.kube/
      readOnly: true
    - name: kubeconf2
      mountPath: /root/kube/.kube/
      readOnly: true
    - name: db-data-path
      mountPath: /test
      readOnly: false
  nodeSelector:
    kubernetes.io/hostname: idc-sh002
  tolerations:
  - key: worker
    operator: Equal
    value: performance
    effect: NoSchedule
  volumes:
  - name: kubeconf
    secret:
      secretName: test-cluster-config
  - name: kubeconf2
    secret:
      secretName: idc-cluster-config
  - name: db-data-path
    flexVolume:
      driver: "fstab/cifs"
      fsType: "cifs"
      secretRef:
        name: "cifs-test-secret"
      options:
        networkPath: "//172.16.70.249/test"
        mountOptions: "vers=1.0"